
server.port=8000

spring.mongodb.uri=mongodb+srv://yashmathuria80_db_user:1lXpCEWBKLuj4JoR@cluster0.iaqgdoy.mongodb.net/uimigrationdb?retryWrites=true&w=majority
agent.base-url=http://127.0.0.1:5001
agent.credentials.username=
agent.credentials.password=
